spring.application.name=@project.name@
spring.application.version=@project.version@
spring.application.build=@build.timestamp@
spring.application.shared-version=@git.branch@#@git.commit.id.abbrev@

restopolis.url=https://ssl.education.lu/eRestauration/CustomerServices/Menu
restopolis.cookies=CustomerServices.Restopolis.SelectedRestaurant=%TARGET%; CustomerServices.Restopolis.SelectedService=15; CustomerServices.Restopolis.DisplayAllergens=false

server.port=3069
server.address=0.0.0.0
